In [26]:
import pandas as pd

In [27]:
df = pd.read_excel('Datos/sprint8_complex.xlsx', skiprows=3)
df.rename(columns={'Unnamed: 0':'Id'}, inplace=True)

In [ ]:
# ¿Existen identificadores únicos (DNI) para cada persona?
# No. Algunos están duplicados.
# En el caso del DNI '90585882A'.
#   Id 104, formato de salario inadecuado.
#   Id 114, número de hijos inválido.
#   Id 281, formato de salario inadecuado.
#   Id 25, 913 y 1000, datos duplicados excepto en campo salario. Conservado el último considerando que son los datos más actualizados.
# En el caso del DNI '55283701C'.
#   Id 36 y 40, datos duplicados. Por defecto se mantiene el primero.
# En el caso del DNI '54013571W'.
#   Id 142, valores contradictorios en 'Fills' y 'No Fills'.
# En el caso del DNI '15909601K'.
#   Id 250, formato de salario inadecuado, valores contradictorios en 'Fills' y 'No Fills'.
# En el caso del DNI '97954019T'.
#   Id 372 y 40, datos duplicados. Por defecto se mantiene el primero.
# En el caso del DNI '49529438G'.
#   Id 692, valor de salario mensual sin coma de millar, número de hijos inválido.


# » Què faràs amb les files duplicades o registres repetits?
# » Hi ha valors obligatoris que falten o informació incoherent?
# » Detectes formats incorrectes, errors de codificació o valors impossibles?

display(df.query('DNI.str.startswith("49529438G")'))

dupe_counter = 0
for i, dupe in enumerate(df['DNI'].duplicated(keep=False)):
    if dupe == True:
        dupe_counter += 1
        display(df.iloc[i])


# print(dupe_counter)

,Id,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
558,558,Alexia,Pérez Díaz,49529438G,Espanya,Màlaga,12.0,10.0,1981.0,Dona,"1,176 €",NaN,True,Grup A,Data Analyst,0.0,False,NaN,NaN,38.0
692,692,Alexia,Pérez Díaz,49529438G,Espanya,Màlaga,12.0,10.0,1981.0,Dona,1663€,NaN,True,Grup C,Cap de projecte,NaN,True,80000.0,10.7,16.9

Id                                       25
Nom                                    Sara
Cognoms                               Serra
DNI                               90585882A
País d'origen                       Espanya
Ciutat                            Tarragona
Dia de Naixement                       28.0
Mes de Naixement                        5.0
Any de Naixement                     2002.0
Gènere                                    D
Salari mensual                        993 €
Fills                                   NaN
No Fills                               True
Grup Professional                    Grup A
Càrrec                        Administratiu
Nombre_fills                            0.0
Te_cotxe                              False
Km_anuals                               NaN
Consum_mitja_L_100km                    NaN
Temperatura_mitjana_ciutat             15.8
Name: 25, dtype: object

Id                                        464
Nom                                       Ida
Cognoms                       Karlsen Eriksen
DNI                                 55283701C
País d'origen                         Noruega
Ciutat                                   Oslo
Dia de Naixement                          2.0
Mes de Naixement                          9.0
Any de Naixement                       1992.0
Gènere                                      D
Salari mensual                        1,614 €
Fills                                    True
No Fills                                  NaN
Grup Professional                      Grup B
Càrrec                               Analista
Nombre_fills                              3.0
Te_cotxe                                  NaN
Km_anuals                                 NaN
Consum_mitja_L_100km                      NaN
Temperatura_mitjana_ciutat               10.6
Name: 36, dtype: object

Id                                       1001
Nom                                       Ida
Cognoms                       Karlsen Eriksen
DNI                                 55283701C
País d'origen                         Noruega
Ciutat                                   Oslo
Dia de Naixement                          2.0
Mes de Naixement                          9.0
Any de Naixement                       1992.0
Gènere                                      D
Salari mensual                        1,614 €
Fills                                    True
No Fills                                  NaN
Grup Professional                      Grup B
Càrrec                               Analista
Nombre_fills                              3.0
Te_cotxe                                  NaN
Km_anuals                                 NaN
Consum_mitja_L_100km                      NaN
Temperatura_mitjana_ciutat               10.6
Name: 40, dtype: object

Id                                      89
Nom                                Guillem
Cognoms                        Pujol Costa
DNI                              54013571W
País d'origen                      Espanya
Ciutat                            A Coruña
Dia de Naixement                      17.0
Mes de Naixement                       7.0
Any de Naixement                    1983.0
Gènere                                   D
Salari mensual                     1.574 €
Fills                                 True
No Fills                               NaN
Grup Professional                   Grup B
Càrrec                        Project lead
Nombre_fills                           4.0
Te_cotxe                             False
Km_anuals                              NaN
Consum_mitja_L_100km                   NaN
Temperatura_mitjana_ciutat            14.6
Name: 89, dtype: object

Id                                              104
Nom                                           Oriol
Cognoms                                 Vila Casals
DNI                                       90585882A
País d'origen                               Espanya
Ciutat                                       Madrid
Dia de Naixement                               30.0
Mes de Naixement                                9.0
Any de Naixement                             1964.0
Gènere                                            H
Salari mensual                           1987 euros
Fills                                           NaN
No Fills                                       True
Grup Professional                            Grup B
Càrrec                        Responsable de vendes
Nombre_fills                                    0.0
Te_cotxe                                      False
Km_anuals                                       NaN
Consum_mitja_L_100km                            NaN
Temperatura_mitjana_ciutat                     13.5
Name: 104, dtype: object

Id                                     114
Nom                                    Pol
Cognoms                              Serra
DNI                              90585882A
País d'origen                      Espanya
Ciutat                              Girona
Dia de Naixement                       4.0
Mes de Naixement                      12.0
Any de Naixement                    1960.0
Gènere                                   H
Salari mensual                     1,178 €
Fills                                  NaN
No Fills                              True
Grup Professional                   Grup A
Càrrec                        Data Analyst
Nombre_fills                           NaN
Te_cotxe                             False
Km_anuals                              NaN
Consum_mitja_L_100km                   NaN
Temperatura_mitjana_ciutat            16.2
Name: 114, dtype: object

Id                                  142
Nom                               Marta
Cognoms                            Ruiz
DNI                           54013571W
País d'origen                   Espanya
Ciutat                            Palma
Dia de Naixement                   24.0
Mes de Naixement                    5.0
Any de Naixement                 1982.0
Gènere                                H
Salari mensual                  1,276 €
Fills                              True
No Fills                           True
Grup Professional                Grup A
Càrrec                         Analista
Nombre_fills                        0.0
Te_cotxe                          False
Km_anuals                           NaN
Consum_mitja_L_100km                NaN
Temperatura_mitjana_ciutat         15.7
Name: 142, dtype: object

Id                                        250
Nom                                      Laia
Cognoms                          Navarro Vila
DNI                                 15909601K
País d'origen                         Espanya
Ciutat                                 Bilbao
Dia de Naixement                         30.0
Mes de Naixement                          5.0
Any de Naixement                       1958.0
Gènere                                      D
Salari mensual                     1235 euros
Fills                                    True
No Fills                                 True
Grup Professional                      Grup D
Càrrec                        Analista junior
Nombre_fills                              0.0
Te_cotxe                                False
Km_anuals                                 NaN
Consum_mitja_L_100km                      NaN
Temperatura_mitjana_ciutat               10.3
Name: 250, dtype: object

Id                                   281
Nom                               Xavier
Cognoms                            Vidal
DNI                            90585882A
País d'origen                    Espanya
Ciutat                           Alacant
Dia de Naixement                     2.0
Mes de Naixement                     7.0
Any de Naixement                  1958.0
Gènere                                 H
Salari mensual                1179 euros
Fills                                NaN
No Fills                             NaN
Grup Professional                 Grup A
Càrrec                         Tècnic IT
Nombre_fills                         0.0
Te_cotxe                            True
Km_anuals                        63574.0
Consum_mitja_L_100km                 6.0
Temperatura_mitjana_ciutat          16.8
Name: 281, dtype: object

Id                                              372
Nom                                            Alba
Cognoms                                       Muñoz
DNI                                       97954019T
País d'origen                               Espanya
Ciutat                                       Bilbao
Dia de Naixement                               25.0
Mes de Naixement                               10.0
Any de Naixement                             1983.0
Gènere                                            D
Salari mensual                              1,409 €
Fills                                           NaN
No Fills                                       True
Grup Professional                            Grup B
Càrrec                        Responsable de vendes
Nombre_fills                                    0.0
Te_cotxe                                        NaN
Km_anuals                                       NaN
Consum_mitja_L_100km                            NaN
Temperatura_mitjana_ciutat                     14.7
Name: 372, dtype: object

Id                                     558
Nom                                 Alexia
Cognoms                         Pérez Díaz
DNI                              49529438G
País d'origen                      Espanya
Ciutat                              Màlaga
Dia de Naixement                      12.0
Mes de Naixement                      10.0
Any de Naixement                    1981.0
Gènere                                Dona
Salari mensual                     1,176 €
Fills                                  NaN
No Fills                              True
Grup Professional                   Grup A
Càrrec                        Data Analyst
Nombre_fills                           0.0
Te_cotxe                             False
Km_anuals                              NaN
Consum_mitja_L_100km                   NaN
Temperatura_mitjana_ciutat            38.0
Name: 558, dtype: object

Id                                  604
Nom                                Laia
Cognoms                         Navarro
DNI                           15909601K
País d'origen                   Espanya
Ciutat                           Bilbao
Dia de Naixement                   30.0
Mes de Naixement                    5.0
Any de Naixement                 1958.0
Gènere                                D
Salari mensual                  1,676 €
Fills                              True
No Fills                          False
Grup Professional                Grup A
Càrrec                         Analista
Nombre_fills                        1.0
Te_cotxe                           True
Km_anuals                          50.0
Consum_mitja_L_100km                NaN
Temperatura_mitjana_ciutat         14.2
Name: 604, dtype: object

Id                                     654
Nom                                  Oriol
Cognoms                              Gómez
DNI                              16618423V
País d'origen                      Espanya
Ciutat                              Madrid
Dia de Naixement                      10.0
Mes de Naixement                       1.0
Any de Naixement                    1968.0
Gènere                                Home
Salari mensual                  1731 euros
Fills                                 True
No Fills                               NaN
Grup Professional                   Grup B
Càrrec                        Data analyst
Nombre_fills                           4.0
Te_cotxe                               NaN
Km_anuals                              NaN
Consum_mitja_L_100km                   NaN
Temperatura_mitjana_ciutat             NaN
Name: 654, dtype: object

Id                                        692
Nom                                    Alexia
Cognoms                            Pérez Díaz
DNI                                 49529438G
País d'origen                         Espanya
Ciutat                                 Màlaga
Dia de Naixement                         12.0
Mes de Naixement                         10.0
Any de Naixement                       1981.0
Gènere                                   Dona
Salari mensual                          1663€
Fills                                     NaN
No Fills                                 True
Grup Professional                      Grup C
Càrrec                        Cap de projecte
Nombre_fills                              NaN
Te_cotxe                                 True
Km_anuals                             80000.0
Consum_mitja_L_100km                     10.7
Temperatura_mitjana_ciutat               16.9
Name: 692, dtype: object

Id                                              730
Nom                                         Claudia
Cognoms                                  Gil Ferrer
DNI                                       55297384F
País d'origen                               Espanya
Ciutat                                     València
Dia de Naixement                                1.0
Mes de Naixement                               11.0
Any de Naixement                             1981.0
Gènere                                            H
Salari mensual                              1.789 €
Fills                                           NaN
No Fills                                       True
Grup Professional                            Grup B
Càrrec                        Responsable de vendes
Nombre_fills                                    0.0
Te_cotxe                                       True
Km_anuals                                   29952.0
Consum_mitja_L_100km                            9.2
Temperatura_mitjana_ciutat                     20.3
Name: 730, dtype: object

Id                                  754
Nom                               Oriol
Cognoms                           Gómez
DNI                           16618423V
País d'origen                   Espanya
Ciutat                        Barcelona
Dia de Naixement                   10.0
Mes de Naixement                    1.0
Any de Naixement                 1968.0
Gènere                             Home
Salari mensual                  2.358 €
Fills                              True
No Fills                            NaN
Grup Professional                   NaN
Càrrec                              NaN
Nombre_fills                        4.0
Te_cotxe                            NaN
Km_anuals                           NaN
Consum_mitja_L_100km                NaN
Temperatura_mitjana_ciutat          NaN
Name: 754, dtype: object

Id                                  757
Nom                               Oriol
Cognoms                          Ferrer
DNI                           52590001R
País d'origen                   Espanya
Ciutat                         Zaragoza
Dia de Naixement                   15.0
Mes de Naixement                    7.0
Any de Naixement                 1973.0
Gènere                                D
Salari mensual                     786€
Fills                               NaN
No Fills                           True
Grup Professional                Grup A
Càrrec                         Analista
Nombre_fills                        0.0
Te_cotxe                           True
Km_anuals                       81381.0
Consum_mitja_L_100km                6.5
Temperatura_mitjana_ciutat         13.9
Name: 757, dtype: object

Id                                     758
Nom                                  Oriol
Cognoms                              Gómez
DNI                              16618423V
País d'origen                      Espanya
Ciutat                              Màlaga
Dia de Naixement                      10.0
Mes de Naixement                       1.0
Any de Naixement                    1968.0
Gènere                                   H
Salari mensual                  1879 euros
Fills                                 True
No Fills                               NaN
Grup Professional                   Grup B
Càrrec                        Data Analyst
Nombre_fills                           4.0
Te_cotxe                             False
Km_anuals                              NaN
Consum_mitja_L_100km                   NaN
Temperatura_mitjana_ciutat             NaN
Name: 758, dtype: object

Id                                              759
Nom                                           Oriol
Cognoms                                       Gómez
DNI                                       16618423V
País d'origen                               Espanya
Ciutat                                      Sevilla
Dia de Naixement                               10.0
Mes de Naixement                                1.0
Any de Naixement                             1968.0
Gènere                                          NaN
Salari mensual                              2,000 €
Fills                                           NaN
No Fills                                        NaN
Grup Professional                            Grup A
Càrrec                        Responsable de vendes
Nombre_fills                                    5.0
Te_cotxe                                        NaN
Km_anuals                                       NaN
Consum_mitja_L_100km                            NaN
Temperatura_mitjana_ciutat                     20.7
Name: 759, dtype: object

Id                                      913
Nom                                    Sara
Cognoms                               Serra
DNI                               90585882A
País d'origen                       Espanya
Ciutat                            Tarragona
Dia de Naixement                       28.0
Mes de Naixement                        5.0
Any de Naixement                     2002.0
Gènere                                 Dona
Salari mensual                      1,000 €
Fills                                   NaN
No Fills                               True
Grup Professional                    Grup A
Càrrec                        Administratiu
Nombre_fills                            0.0
Te_cotxe                              False
Km_anuals                               NaN
Consum_mitja_L_100km                    NaN
Temperatura_mitjana_ciutat             15.8
Name: 913, dtype: object

Id                                     1000
Nom                                    Sara
Cognoms                               Serra
DNI                               90585882A
País d'origen                       Espanya
Ciutat                            Tarragona
Dia de Naixement                       28.0
Mes de Naixement                        5.0
Any de Naixement                     2002.0
Gènere                                    D
Salari mensual                      1,073 €
Fills                                   NaN
No Fills                               True
Grup Professional                    Grup A
Càrrec                        Administratiu
Nombre_fills                            0.0
Te_cotxe                              False
Km_anuals                               NaN
Consum_mitja_L_100km                    NaN
Temperatura_mitjana_ciutat             15.8
Name: 1000, dtype: object

Id                                             1002
Nom                                            Alba
Cognoms                                       Muñoz
DNI                                       97954019T
País d'origen                               Espanya
Ciutat                                       Bilbao
Dia de Naixement                               25.0
Mes de Naixement                               10.0
Any de Naixement                             1983.0
Gènere                                            D
Salari mensual                              1,409 €
Fills                                           NaN
No Fills                                       True
Grup Professional                            Grup B
Càrrec                        Responsable de vendes
Nombre_fills                                    0.0
Te_cotxe                                        NaN
Km_anuals                                       NaN
Consum_mitja_L_100km                            NaN
Temperatura_mitjana_ciutat                     14.7
Name: 1002, dtype: object

Id                                             1003
Nom                                         Claudia
Cognoms                                  Gil Ferrer
DNI                                       55297384F
País d'origen                               Espanya
Ciutat                                     València
Dia de Naixement                                1.0
Mes de Naixement                               11.0
Any de Naixement                             1981.0
Gènere                                            H
Salari mensual                              1.789 €
Fills                                           NaN
No Fills                                       True
Grup Professional                            Grup B
Càrrec                        Responsable de vendes
Nombre_fills                                    0.0
Te_cotxe                                       True
Km_anuals                                   29952.0
Consum_mitja_L_100km                            9.2
Temperatura_mitjana_ciutat                     20.3
Name: 1003, dtype: object

Id                                 1004
Nom                               Oriol
Cognoms                          Ferrer
DNI                           52590001R
País d'origen                   Espanya
Ciutat                         Zaragoza
Dia de Naixement                   15.0
Mes de Naixement                    7.0
Any de Naixement                 1973.0
Gènere                                D
Salari mensual                     786€
Fills                               NaN
No Fills                           True
Grup Professional                Grup A
Càrrec                         Analista
Nombre_fills                        0.0
Te_cotxe                           True
Km_anuals                       81381.0
Consum_mitja_L_100km                6.5
Temperatura_mitjana_ciutat         13.9
Name: 1004, dtype: object

In [29]:
def repair_mojibake(texto):
    if isinstance(texto, str):
        try:
            return texto.encode('windows-1252').decode('utf-8')
        except (UnicodeEncodeError, UnicodeDecodeError):
            return texto
    return texto

nombres_columnas = [repair_mojibake(col) for col in df.columns]
df.columns = nombres_columnas
for columna in df:
    df[columna] = df[columna].apply(repair_mojibake)

df.head(10)

,Id,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 €",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 €",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,Tècnic IT,4.0,NaN,NaN,NaN,16.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 €",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 €",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
5,5,Alexia,Puig,25014631B,Espanya,Las Palmas de Gran Canaria,1.0,8.0,1978.0,D,"2,069 €",NaN,True,Grup B,Cap de projecte,0.0,NaN,NaN,NaN,19.9
6,6,David,Gómez Vila,36998038E,Espanya,Palma,25.0,9.0,1971.0,D,"2,349 €",NaN,True,Grup B,Cap de projecte,NaN,True,6196.0,10.6,17.8
7,7,Carmen,López,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 €",True,NaN,Grup C,Responsable de vendes,4.0,True,20000.0,5.9,15.4
8,540,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 €",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
9,9,Alba,García,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 €",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1