In [7]:
import pandas as pd

In [8]:
df = pd.read_excel('Datos/sprint8_complex.xlsx', skiprows=3)
df.rename(columns={'Unnamed: 0':'Id'}, inplace=True)

In [9]:
# ¿Existen identificadores únicos (DNI) para cada persona?
# No, pues algunos están duplicados.
# En el caso del DNI '90585882A'.
#   Id 104, formato de salario inadecuado.
#   Id 114, número de hijos inválido.
#   Id 281, formato de salario inadecuado.
#   Id 25, 913 y 1000, datos duplicados excepto en campo salario. Conservado el último considerando que son los datos más actualizados.
# En el caso del DNI '55283701C'.
#   Id 36 y 40, datos duplicados. Por defecto se mantiene el primero.
# En el caso del DNI '54013571W'.
#   Id 142, valores contradictorios en 'Fills' y 'No Fills'.
# En el caso del DNI '15909601K'.
#   Id 250, formato de salario inadecuado, valores contradictorios en 'Fills' y 'No Fills'.
# En el caso del DNI '97954019T'.
#   Id 372 y 1002, datos duplicados. Por defecto se mantiene el primero.
# En el caso del DNI '49529438G'.
#   Id 692, valor de salario mensual sin coma de millar, número de hijos inválido.
# En el caso del DNI '16618423V'.
#   Id 654, 754, 758 y 759, presentan inconsistencias. El más adecuado es el 758, que únicamente presenta un formato de salario inadecuado.
# En el caso del DNI '55297384F'.
#   Id 730 y 1003, datos duplicados. Por defecto se mantiene el primero.
# En el caso del DNI '52590001R'.
#   Id 757 y 1004, datos duplicados. Por defecto se mantiene el primero.

dupes_list = []
for i, dupe in enumerate(df['DNI'].duplicated(keep=False)):
    if dupe == True:
        dupes_list.append(df.iloc[i])
        # display(df.iloc[i])
dupes_df = pd.DataFrame(dupes_list)

display(dupes_df.sort_values('DNI'))

,Id,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
604,604,Laia,Navarro,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,"1,676 â‚¬",True,False,Grup A,Analista,1.0,True,50.0,NaN,14.2
250,250,Laia,Navarro Vila,15909601K,Espanya,Bilbao,30.0,5.0,1958.0,D,1235 euros,True,True,Grup D,Analista junior,0.0,False,NaN,NaN,10.3
759,759,Oriol,GÃ³mez,16618423V,Espanya,Sevilla,10.0,1.0,1968.0,NaN,"2,000 â‚¬",NaN,NaN,Grup A,Responsable de vendes,5.0,NaN,NaN,NaN,20.7
758,758,Oriol,GÃ³mez,16618423V,Espanya,MÃ laga,10.0,1.0,1968.0,H,1879 euros,True,NaN,Grup B,Data Analyst,4.0,False,NaN,NaN,NaN
754,754,Oriol,GÃ³mez,16618423V,Espanya,Barcelona,10.0,1.0,1968.0,Home,2.358 â‚¬,True,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
654,654,Oriol,GÃ³mez,16618423V,Espanya,Madrid,10.0,1.0,1968.0,Home,1731 euros,True,NaN,Grup B,Data analyst,4.0,NaN,NaN,NaN,NaN
692,692,Alexia,PÃ©rez DÃ­az,49529438G,Espanya,MÃ laga,12.0,10.0,1981.0,Dona,1663â‚¬,NaN,True,Grup C,Cap de projecte,NaN,True,80000.0,10.7,16.9
558,558,Alexia,PÃ©rez DÃ­az,49529438G,Espanya,MÃ laga,12.0,10.0,1981.0,Dona,"1,176 â‚¬",NaN,True,Grup A,Data Analyst,0.0,False,NaN,NaN,38.0
757,757,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
1004,1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
142,142,Marta,Ruiz,54013571W,Espanya,Palma,24.0,5.0,1982.0,H,"1,276 â‚¬",True,True,Grup A,Analista,0.0,False,NaN,NaN,15.7
89,89,Guillem,Pujol Costa,54013571W,Espanya,A CoruÃ±a,17.0,7.0,1983.0,D,1.574 â‚¬,True,NaN,Grup B,Project lead,4.0,False,NaN,NaN,14.6
40,1001,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 â‚¬",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
36,464,Ida,Karlsen Eriksen,55283701C,Noruega,Oslo,2.0,9.0,1992.0,D,"1,614 â‚¬",True,NaN,Grup B,Analista,3.0,NaN,NaN,NaN,10.6
1003,1003,Claudia,Gil Ferrer,55297384F,Espanya,ValÃ¨ncia,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
730,730,Claudia,Gil Ferrer,55297384F,Espanya,ValÃ¨ncia,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
281,281,Xavier,Vidal,90585882A,Espanya,Alacant,2.0,7.0,1958.0,H,1179 euros,NaN,NaN,Grup A,TÃ¨cnic IT,0.0,True,63574.0,6.0,16.8
114,114,Pol,Serra,90585882A,Espanya,Girona,4.0,12.0,1960.0,H,"1,178 â‚¬",NaN,True,Grup A,Data Analyst,NaN,False,NaN,NaN,16.2
104,104,Oriol,Vila Casals,90585882A,Espanya,Madrid,30.0,9.0,1964.0,H,1987 euros,NaN,True,Grup B,Responsable de vendes,0.0,False,NaN,NaN,13.5
913,913,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,Dona,"1,000 â‚¬",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1000,1000,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,"1,073 â‚¬",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
25,25,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,993 â‚¬,NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1002,1002,Alba,MuÃ±oz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
372,372,Alba,MuÃ±oz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7

In [10]:
# ¿Qué harás con las filas duplicadas o registros repetidos?
# Eliminar los duplicados siguiendo el criterio explicado anteriormente. 
pre_drop = len(df)
df.drop_duplicates(subset=df.columns.difference(['Id']), inplace=True)
post_drop = len(df)

diff = pre_drop - post_drop

display(df)
print(str(diff)+' registros eliminados.')

,Id,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
2,2,Noa,Serra,14308421X,Espanya,Alacant,27.0,4.0,1961.0,D,1358 euros,True,NaN,Grup A,TÃ¨cnic IT,4.0,NaN,NaN,NaN,16.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
4,4,David,Vila,82070937P,Espanya,Bilbao,29.0,11.0,1965.0,Dona,"1,284 â‚¬",NaN,True,Grup B,Administratiu,NaN,True,NaN,11.8,13.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999,999,AdriÃ,Vila DÃ­az,57511543T,Espanya,Palma,31.0,12.0,1991.0,H,"2,010 â‚¬",True,NaN,Grup C,Analista,1.0,False,NaN,NaN,-10.0
1000,1000,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,"1,073 â‚¬",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1001,651,Kasper,Pettersen,62042563B,Noruega,Oslo,11.0,5.0,1996.0,D,2.290 â‚¬,NaN,True,Grup B,Senior analyst,0.0,True,80000.0,0.5,6.5
1005,1005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

4 registros eliminados.

In [18]:
# ¿Hay valores obligatorios que faltan o información incoherente?
# Sí.

df.dropna(subset=df.columns.difference(['Fills', 'No Fills', 'Km_anuals', 'Consum_mitja_L_100km']), inplace=True)
df.dropna(how='all', subset=['Fills', 'No Fills'], inplace=True)

for indx, [fills, no_fills] in enumerate(zip(df['Fills'], df['No Fills'])):
    if fills == no_fills:
        print(indx)
        df.drop(index=indx, errors='ignore')

display(df)

7
54
61
75
86
93
105
106
113
121
123
166
167
187
224
231
255
260
287
288
328
337
343
345

,Id,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 â‚¬",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,7,Carmen,LÃ³pez,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 â‚¬",True,NaN,Grup C,Responsable de vendes,4.0,True,20000.0,5.9,15.4
9,9,Alba,GarcÃ­a,75181648S,Espanya,Las Palmas de Gran Canaria,32.0,0.0,1940.0,H,"1,450 â‚¬",True,NaN,Grup A,Senior analyst,4.0,False,NaN,NaN,20.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,988,David,Roca PÃ©rez,31701972H,Espanya,Girona,3.0,5.0,1975.0,H,"1,002 â‚¬",True,NaN,Grup A,Analista,1.0,True,50453.0,11.8,9.5
989,989,Marta,HernÃ¡ndez Puig,45997422C,Espanya,A CoruÃ±a,25.0,10.0,1969.0,D,"1,183 â‚¬",NaN,True,Grup A,Analista junior,0.0,True,27921.0,NaN,11.7
999,999,AdriÃ,Vila DÃ­az,57511543T,Espanya,Palma,31.0,12.0,1991.0,H,"2,010 â‚¬",True,NaN,Grup C,Analista,1.0,False,NaN,NaN,-10.0
1000,1000,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,"1,073 â‚¬",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1001,651,Kasper,Pettersen,62042563B,Noruega,Oslo,11.0,5.0,1996.0,D,2.290 â‚¬,NaN,True,Grup B,Senior analyst,0.0,True,80000.0,0.5,6.5

In [ ]:
# ¿Detectas formatos incorrectos, errores de codificación o valores imposibles?
# Sí.

# Para convertir formatos incorrectos:

def hola_mundo():
    return


# Para arreglar el error de codificación:

def repair_mojibake(texto):
    if isinstance(texto, str):
        try:
            return texto.encode('windows-1252').decode('utf-8')
        except (UnicodeEncodeError, UnicodeDecodeError):
            return texto
    return texto

nombres_columnas = [repair_mojibake(col) for col in df.columns]
df.columns = nombres_columnas
for columna in df:
    df[columna] = df[columna].apply(repair_mojibake)


# Para eliminar los registros con valores imposibles:

def saludos_raimundo():
    return

display(df)

,Id,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Càrrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
0,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 €",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
1,1,Marc,Muñoz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 €",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
3,3,Pol,Gil,58586340F,Espanya,Sevilla,13.0,10.0,1985.0,H,"1,478 €",True,NaN,Grup B,Data Analyst,2.0,False,NaN,NaN,18.3
7,7,Carmen,López,47376585K,Espanya,Barcelona,8.0,9.0,1962.0,H,"2,855 €",True,NaN,Grup C,Responsable de vendes,4.0,True,20000.0,5.9,15.4
8,540,Nora,Andersen Pedersen,37289414J,Noruega,Stavanger,8.0,3.0,1963.0,D,"1,338 €",NaN,True,Grup B,Analista junior,0.0,False,NaN,NaN,7.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,988,David,Roca Pérez,31701972H,Espanya,Girona,3.0,5.0,1975.0,H,"1,002 €",True,NaN,Grup A,Analista,1.0,True,50453.0,11.8,9.5
989,989,Marta,Hernández Puig,45997422C,Espanya,A Coruña,25.0,10.0,1969.0,D,"1,183 €",NaN,True,Grup A,Analista junior,0.0,True,27921.0,NaN,11.7
999,999,Adrià,Vila Díaz,57511543T,Espanya,Palma,31.0,12.0,1991.0,H,"2,010 €",True,NaN,Grup C,Analista,1.0,False,NaN,NaN,-10.0
1000,1000,Sara,Serra,90585882A,Espanya,Tarragona,28.0,5.0,2002.0,D,"1,073 €",NaN,True,Grup A,Administratiu,0.0,False,NaN,NaN,15.8
1001,651,Kasper,Pettersen,62042563B,Noruega,Oslo,11.0,5.0,1996.0,D,2.290 €,NaN,True,Grup B,Senior analyst,0.0,True,80000.0,0.5,6.5